/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sistema.CRUD;
import sistema.UsuarioDTO;


    

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    private int perfil;

    public void setupPerfil(int perfil){
        
        this.perfil = perfil;
        
    }

    
    
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogin = new javax.swing.JPanel();
        superior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelCentral = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtUsuarioLogin = new javax.swing.JTextField();
        txtSenhaLogin = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoUsuarioLogin = new org.bolivia.combo.SComboBoxBlue();
        painelInf = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(430, 540));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelLogin.setOpaque(false);
        painelLogin.setLayout(new java.awt.BorderLayout());

        superior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        superior.setToolTipText("");
        superior.setOpaque(false);
        superior.setPreferredSize(new java.awt.Dimension(411, 180));
        superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("  LOGIN SISTEMA");
        jLabel1.setOpaque(true);
        superior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/imgLogin.png"))); // NOI18N
        superior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 180));

        painelLogin.add(superior, java.awt.BorderLayout.PAGE_START);

        painelCentral.setOpaque(false);
        painelCentral.setLayout(new java.awt.BorderLayout(0, 10));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Realize seu Login");
        painelCentral.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuarioLogin.setBackground(new java.awt.Color(51, 51, 255));
        txtUsuarioLogin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtUsuarioLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioLogin.setBorder(null);
        jPanel1.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, 30));

        txtSenhaLogin.setBackground(new java.awt.Color(51, 51, 255));
        txtSenhaLogin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtSenhaLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtSenhaLogin.setBorder(null);
        jPanel1.add(txtSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/user.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/campoLoginPass.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/campoLoginUs.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        cmbTipoUsuarioLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        cmbTipoUsuarioLogin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO USUÁRIO", "ADMINISTRADOR", "CAIXA", " " }));
        cmbTipoUsuarioLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(cmbTipoUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 240, 50));

        painelCentral.add(jPanel1, java.awt.BorderLayout.CENTER);

        painelInf.setOpaque(false);
        painelInf.setPreferredSize(new java.awt.Dimension(50, 65));
        painelInf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/entrar2.png"))); // NOI18N
        btnEntrar.setBorderPainted(false);
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/entrar1.png"))); // NOI18N
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        painelInf.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, 50));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair2.png"))); // NOI18N
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair1.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        painelInf.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        painelCentral.add(painelInf, java.awt.BorderLayout.PAGE_END);

        painelLogin.add(painelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        dispose();

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        try {

            String user = txtUsuarioLogin.getText();
            String senha = new String(txtSenhaLogin.getPassword());
            String tipoUser = (String)cmbTipoUsuarioLogin.getSelectedItem();

            UsuarioDTO U = new UsuarioDTO();

            U.setUser(user);
            U.setSenha(senha);
            U.setTipoUser(tipoUser);

            CRUD verifica = new CRUD();
            
            ResultSet rsCRUD = verifica.confereLoginUser(U);
          
            
            
            if (rsCRUD.next()) {
                
                telaPrincipal abreTela = new telaPrincipal();
                abreTela.setVisible(true);

                dispose();
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Erro,Usuario ou senha inválidos");
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro frmLogin");

        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                login tela = new login();

                tela.setLocationRelativeTo(null);

                new login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    public static org.bolivia.combo.SComboBoxBlue cmbTipoUsuarioLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelInf;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel superior;
    public static javax.swing.JPasswordField txtSenhaLogin;
    public static javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
