/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import static principal.login.cmbTipoUsuarioLogin;
import produtos.FrmProdutos;
import produtos.frmListaProd;
import usuarios.frmUsuarios;
import vendas.frmCaixa;
import static principal.login.txtUsuarioLogin;



/**
 *
 * @author Admin
 */
public class telaPrincipal extends javax.swing.JFrame {
    
     
    
     

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        txtlogouser.setText(txtUsuarioLogin.getText());
        txtTipoUser.setText((String)cmbTipoUsuarioLogin.getSelectedItem());
 
        Calendar rightNow = Calendar.getInstance();
        int horaDia = rightNow.get(Calendar.HOUR_OF_DAY);
        int minutoDia = rightNow.get(Calendar.MINUTE);
        hora.setText(String.valueOf(horaDia)+":"+String.valueOf(minutoDia));
        
        int diaHoje = rightNow.get(Calendar.DATE);
        int mesHoje = rightNow.get(Calendar.DAY_OF_MONTH);
        int AnoHoje = rightNow.get(Calendar.YEAR);
        data.setText(String.valueOf(diaHoje)+"/"+"11"+"/"+String.valueOf(AnoHoje));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelprincipal = new javax.swing.JPanel();
        painelCabecalho = new javax.swing.JPanel();
        txtlogouser = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JButton();
        logoDesconectar = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hora = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTipoUser1 = new javax.swing.JLabel();
        txtTipoUser = new javax.swing.JLabel();
        carregador1 = new principal.Carregador();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setLocation(new java.awt.Point(200, 100));
        setPreferredSize(new java.awt.Dimension(1200, 640));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelprincipal.setBackground(new java.awt.Color(204, 204, 204));
        painelprincipal.setLayout(new java.awt.BorderLayout());

        painelCabecalho.setBackground(new java.awt.Color(204, 204, 204));
        painelCabecalho.setBorder(null);
        painelCabecalho.setPreferredSize(new java.awt.Dimension(1200, 140));
        painelCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlogouser.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtlogouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/conectado.png"))); // NOI18N
        txtlogouser.setText("Usuário");
        painelCabecalho.add(txtlogouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 170, -1));

        btnDesconectar.setBorderPainted(false);
        btnDesconectar.setContentAreaFilled(false);
        btnDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 110, 30));

        logoDesconectar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        logoDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/desconec.png"))); // NOI18N
        logoDesconectar.setText("Desconectar...");
        painelCabecalho.add(logoDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, -1, -1));

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario1.png"))); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setBorder(null);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setPreferredSize(new java.awt.Dimension(100, 120));
        btnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario2.png"))); // NOI18N
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 130));

        btnProdutos.setBackground(new java.awt.Color(255, 255, 255));
        btnProdutos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos.png"))); // NOI18N
        btnProdutos.setText("Produtos");
        btnProdutos.setBorder(null);
        btnProdutos.setContentAreaFilled(false);
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdutos.setPreferredSize(new java.awt.Dimension(100, 120));
        btnProdutos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos2.png"))); // NOI18N
        btnProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 130));

        btnCaixa.setBackground(new java.awt.Color(255, 255, 255));
        btnCaixa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/caixa2.png"))); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.setBorder(null);
        btnCaixa.setContentAreaFilled(false);
        btnCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaixa.setPreferredSize(new java.awt.Dimension(100, 120));
        btnCaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/caixa.png"))); // NOI18N
        btnCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 130));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(null);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        hora.setText("  HORA");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        data.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        data.setText("DIA-MES-ANO");
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        painelCabecalho.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipoUser1.setBackground(new java.awt.Color(0, 0, 0));
        txtTipoUser1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtTipoUser1.setText("Tipo:");
        txtTipoUser1.setToolTipText("");
        jPanel2.add(txtTipoUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        txtTipoUser.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtTipoUser.setText("Usuário");
        jPanel2.add(txtTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 30));

        painelCabecalho.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 30));

        painelprincipal.add(painelCabecalho, java.awt.BorderLayout.PAGE_START);

        carregador1.setBackground(new java.awt.Color(255, 255, 204));
        painelprincipal.add(carregador1, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelprincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        
           FrmProdutos produtos = new FrmProdutos();
           frmListaProd produtosView = new frmListaProd();
           principal.telaPrincipal.carregador1.add(produtos).setLocation(1,3);
           principal.telaPrincipal.carregador1.add(produtosView).setLocation(1,3);
           
           if (txtTipoUser.getText() == "ADMINISTRADOR"){
               
               produtos.show();
               
           } else if (txtTipoUser.getText() == "CAIXA"){
               
               JOptionPane.showMessageDialog(null, "Acesso Negado");
               
           } else{
               JOptionPane.showMessageDialog(null, "Erro");
           }
          
        
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
            
           frmUsuarios users = new frmUsuarios();
           principal.telaPrincipal.carregador1.add(users).setLocation(1,3);
           
           if (txtTipoUser.getText() == "ADMINISTRADOR"){
               
               users.show();
               
           } else if (txtTipoUser.getText() == "CAIXA"){
               
               JOptionPane.showMessageDialog(null, "Acesso Negado");
               
           } else{
               JOptionPane.showMessageDialog(null, "Erro");
           }
          
          
    
           
           
            
        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
            
            frmCaixa caixa = new frmCaixa();
            principal.telaPrincipal.carregador1.add(caixa).setLocation(0,0);
    
            caixa.show();
        
        
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
       login l = new login();
       l.show();
       dispose();
    }//GEN-LAST:event_btnDesconectarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnUsuarios;
    public static principal.Carregador carregador1;
    private javax.swing.JLabel data;
    private javax.swing.JLabel hora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoDesconectar;
    private javax.swing.JPanel painelCabecalho;
    public static javax.swing.JPanel painelprincipal;
    private javax.swing.JLabel txtTipoUser;
    private javax.swing.JLabel txtTipoUser1;
    private javax.swing.JLabel txtlogouser;
    // End of variables declaration//GEN-END:variables
}
