/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package usuarios;

import javax.swing.JOptionPane;
import sistema.CRUD;
import static usuarios.frmUsuarios.txtUsuario;

/**
 *
 * @author Admin
 */
public class frmEditar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEditar
     */
    public frmEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbtipoAlteracao = new org.bolivia.combo.SComboBoxBlue();
        jLabel1 = new javax.swing.JLabel();
        txtAlteracao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(309, 326));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtipoAlteracao.setBorder(null);
        cmbtipoAlteracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma alteração", "USUARIO", "TIPO USUARIO", "SENHA USUARIO", " " }));
        cmbtipoAlteracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(cmbtipoAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 212, 40));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Alterar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtAlteracao.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        getContentPane().add(txtAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 212, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText(" Novo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
        String ResultadoTipo = (String) cmbtipoAlteracao.getSelectedItem();
        CRUD alterar = new CRUD();
        
        if (ResultadoTipo=="Selecione uma alteração"){
            
            JOptionPane.showInputDialog("Escolha uma Opção", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        if(ResultadoTipo =="USUARIO"){
            
            alterar.editarUsuario(txtAlteracao.getText(),txtUsuario.getText());
            
        } if(ResultadoTipo =="TIPO USUARIO"){
            
            alterar.editarTipoUser(txtAlteracao.getText(),txtUsuario.getText());
             
        } else{
            
            alterar.editarSenha(txtAlteracao.getText(),txtUsuario.getText());
            
        }
        
       
        dispose();
        
        
      
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private org.bolivia.combo.SComboBoxBlue cmbtipoAlteracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAlteracao;
    // End of variables declaration//GEN-END:variables
}
