package usuarios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.CRUD;
import sistema.ClasseConexao;

/**
 *
 * @author Admin
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMain = new javax.swing.JPanel();
        painelOpcoes = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        painelCabecalho = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        btnBuscaUser = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        iconCodigo = new javax.swing.JLabel();
        iconPreco = new javax.swing.JLabel();
        cmbTipoUsuario = new org.bolivia.combo.SComboBoxBlue();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUser = new javax.swing.JTable();

        setTitle("Usuários");
        setPreferredSize(new java.awt.Dimension(1182, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PainelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("OPÇÕES"));
        painelOpcoes.setMinimumSize(new java.awt.Dimension(703, 142));
        painelOpcoes.setPreferredSize(new java.awt.Dimension(703, 162));
        painelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar Áreas");
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar1.png"))); // NOI18N
        btnLimpar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, 100));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/regis1.png"))); // NOI18N
        btnRegistrar.setText("Resgistrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/regis2.png"))); // NOI18N
        btnRegistrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 100));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, 100));

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setLabel("Excluir");
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar1.png"))); // NOI18N
        btnExcluir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 90, 100));

        PainelMain.add(painelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 520, 151));

        painelCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        painelCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTROS"));
        painelCabecalho.setMinimumSize(new java.awt.Dimension(703, 142));
        painelCabecalho.setPreferredSize(new java.awt.Dimension(703, 162));
        painelCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(0, 102, 153));
        txtUsuario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        painelCabecalho.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 30));

        btnBuscaUser.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscaUser.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnBuscaUser.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaUser.setText("Mostrar Todos Usuários");
        btnBuscaUser.setToolTipText("");
        btnBuscaUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscaUser.setContentAreaFilled(false);
        btnBuscaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscaUser.setOpaque(true);
        btnBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaUserActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 240, 50));

        txtSenha.setBackground(new java.awt.Color(0, 102, 153));
        txtSenha.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(null);
        painelCabecalho.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 180, 30));

        iconCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/nomUs.png"))); // NOI18N
        painelCabecalho.add(iconCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, -1));

        iconPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/senha.png"))); // NOI18N
        painelCabecalho.add(iconPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        cmbTipoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO USUÁRIO", "ADMINISTRADOR", "CAIXA", " " }));
        cmbTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        painelCabecalho.add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/tipousL.png"))); // NOI18N
        painelCabecalho.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 50, -1));

        PainelMain.add(painelCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 168));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(703, 177));

        tabelaUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "USUARIO", "NOME USUÁRIO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUser);

        PainelMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 650, 320));

        getContentPane().add(PainelMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        txtUsuario.setText("");
        txtSenha.setText("");

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        CRUD inserir = new CRUD();
        String ResultadoTipo = (String) cmbTipoUsuario.getSelectedItem();

        if (txtUsuario.getText().isEmpty() || txtSenha.getText().isEmpty() || ResultadoTipo == "TIPO USUÁRIO") {

            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos");
            return;
        }

        inserir.registroUser(txtUsuario.getText(), ResultadoTipo, txtSenha.getText());

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        String ResultadoTipo = (String) cmbTipoUsuario.getSelectedItem();

        if (txtSenha == null || txtUsuario == null) {

            JOptionPane.showInputDialog("Insira os dados de Procura");

        } else {

            frmEditar mostrar = new frmEditar();
            principal.telaPrincipal.carregador1.add(mostrar).setLocation(250, 3);
            mostrar.show();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        CRUD inserir = new CRUD();

        inserir.excluirUser(txtUsuario.getText());


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaUserActionPerformed
        
      CRUD c = new CRUD();
      c.CarregaTabela();

    
    

    }//GEN-LAST:event_btnBuscaUserActionPerformed

                                          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PainelMain;
    private javax.swing.JButton btnBuscaUser;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrar;
    public static org.bolivia.combo.SComboBoxBlue cmbTipoUsuario;
    private javax.swing.JLabel iconCodigo;
    private javax.swing.JLabel iconPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelOpcoes;
    public static javax.swing.JTable tabelaUser;
    public static javax.swing.JPasswordField txtSenha;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}