/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package produtos;

import sistema.CRUD;
import static vendas.frmCaixa.tabelaCaixa;
import static vendas.frmCaixa.txtTotal;

/**
 *
 * @author Admin
 */
public class frmListaProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaProd
     */
    public frmListaProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCodProduto = new javax.swing.JTextField();
        iconBuscarProdutos2 = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(422, 200));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(703, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodProduto.setBackground(new java.awt.Color(0, 102, 153));
        txtCodProduto.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCodProduto.setForeground(new java.awt.Color(255, 255, 255));
        txtCodProduto.setText("CÓDIGO");
        txtCodProduto.setBorder(null);
        jPanel1.add(txtCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 30));

        iconBuscarProdutos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/buscarL.png"))); // NOI18N
        jPanel1.add(iconBuscarProdutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        btnProcurar.setBackground(new java.awt.Color(255, 255, 255));
        btnProcurar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis1.png"))); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.setBorder(null);
        btnProcurar.setBorderPainted(false);
        btnProcurar.setContentAreaFilled(false);
        btnProcurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProcurar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcurar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis2.png"))); // NOI18N
        btnProcurar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnProcurar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 90, 100));

        PP.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 152));

        getContentPane().add(PP);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
     
      CRUD C = new CRUD();
      C.CarregaTabelaProdEspecifico();
      txtCodProduto.setText("");
      
      
        
    }//GEN-LAST:event_btnProcurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PP;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JLabel iconBuscarProdutos2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtCodProduto;
    // End of variables declaration//GEN-END:variables
}
