/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package produtos;

import javax.swing.JOptionPane;
import sistema.CRUD;

/**
 *
 * @author Admin
 */
public class FrmProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProdutos
     */
    public FrmProdutos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPP = new javax.swing.JPanel();
        painelOpcoes = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        painelCabecalho = new javax.swing.JPanel();
        txtCod = new javax.swing.JTextField();
        txtProd = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        iconCodigo = new javax.swing.JLabel();
        iconPreco = new javax.swing.JLabel();
        iconNomeProduto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbtipoProd = new org.bolivia.combo.SComboBoxBlue();
        painelBuscar = new javax.swing.JPanel();
        btnBuscaUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("OPÇÕES"));
        painelOpcoes.setMinimumSize(new java.awt.Dimension(703, 142));
        painelOpcoes.setPreferredSize(new java.awt.Dimension(703, 162));
        painelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar Áreas");
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar1.png"))); // NOI18N
        btnLimpar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 100, 100));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis1.png"))); // NOI18N
        btnRegistrar.setText("Resgistrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis2.png"))); // NOI18N
        btnRegistrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 100));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 100));

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setLabel("Excluir");
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar1.png"))); // NOI18N
        btnExcluir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 90, 100));

        mainPP.add(painelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 425, 151));

        painelCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        painelCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTROS"));
        painelCabecalho.setMinimumSize(new java.awt.Dimension(703, 142));
        painelCabecalho.setPreferredSize(new java.awt.Dimension(703, 162));
        painelCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCod.setBackground(new java.awt.Color(0, 102, 153));
        txtCod.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCod.setForeground(new java.awt.Color(255, 255, 255));
        txtCod.setBorder(null);
        painelCabecalho.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 30));

        txtProd.setBackground(new java.awt.Color(0, 102, 153));
        txtProd.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtProd.setForeground(new java.awt.Color(255, 255, 255));
        txtProd.setBorder(null);
        painelCabecalho.add(txtProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 30));

        txtValor.setBackground(new java.awt.Color(0, 102, 153));
        txtValor.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtValor.setForeground(new java.awt.Color(255, 255, 255));
        txtValor.setBorder(null);
        painelCabecalho.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 180, 30));

        iconCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/codigoL.png"))); // NOI18N
        painelCabecalho.add(iconCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        iconPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/precoL.png"))); // NOI18N
        painelCabecalho.add(iconPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        iconNomeProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/nomeL.png"))); // NOI18N
        painelCabecalho.add(iconNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/tipopro.png"))); // NOI18N
        painelCabecalho.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        cmbtipoProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        cmbtipoProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO PRODUTO", "BEBIDAS", "LIMPEZA", "CARNES", "CONGELADOS", "LACTINEOS", "VERDURAS" }));
        cmbtipoProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        painelCabecalho.add(cmbtipoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 180, 50));

        mainPP.add(painelCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 168));

        painelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        painelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        painelBuscar.setMinimumSize(new java.awt.Dimension(703, 142));
        painelBuscar.setPreferredSize(new java.awt.Dimension(703, 162));
        painelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscaUser.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscaUser.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnBuscaUser.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaUser.setText("Mostrar Todos Produtos");
        btnBuscaUser.setToolTipText("");
        btnBuscaUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscaUser.setContentAreaFilled(false);
        btnBuscaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscaUser.setOpaque(true);
        btnBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaUserActionPerformed(evt);
            }
        });
        painelBuscar.add(btnBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 50));

        mainPP.add(painelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 270, 150));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(703, 177));

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Tipo Produto", "Nome do Produto", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        mainPP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 480, 320));

        getContentPane().add(mainPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtCod.setText("");
        txtProd.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
      CRUD c = new CRUD();
      
      String ResultadoTipo = (String) cmbtipoProd.getSelectedItem();

        if (txtCod.getText().isEmpty() || txtProd.getText().isEmpty() || ResultadoTipo == "TIPO PRODUTO" || txtValor.getText().isEmpty() ) {

            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos");
            return;
        }

        c.registroProd(txtCod.getText(), ResultadoTipo, txtProd.getText(),txtValor.getText());
      
     
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     
        frmEditarProd e = new frmEditarProd();
        
        if (txtCod == null || txtProd == null) {

            JOptionPane.showInputDialog("Insira os dados de Procura");

        } else {

            frmEditarProd mostrar = new frmEditarProd();
            principal.telaPrincipal.carregador1.add(mostrar).setLocation(250, 3);
            mostrar.show();
        }
        
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       
      CRUD c = new CRUD();
      c.excluirProduto(txtCod.getText());
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaUserActionPerformed

        CRUD c = new CRUD();
        c.CarregaTabelaProd();

    }//GEN-LAST:event_btnBuscaUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaUser;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrar;
    private org.bolivia.combo.SComboBoxBlue cmbtipoProd;
    private javax.swing.JLabel iconCodigo;
    private javax.swing.JLabel iconNomeProduto;
    private javax.swing.JLabel iconPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPP;
    private javax.swing.JPanel painelBuscar;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelOpcoes;
    public static javax.swing.JTable tabelaProdutos;
    public static javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtProd;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
